export const initialClasses = {
  "Master Cycle": [],
  "Gracie Combatives": [
    "Trap and Roll Escape - Mount (GU 1) | Leg Hook Takedown (GU 6)",
    "Americana Armlock - Mount (GU 2) | Clinch (Aggressive Opponent) (GU 7)",
    "Positional Control - Mount (GU 3) | Body Fold Takedown (GU 14)",
    "Take the Back + R.N.C. - Mount (GU 4 + 5) | Clinch (Conservative Opponent) (GU 15)",
    "Punch Block Series (1-4) - Guard (GU 8) | Guillotine Choke (Standing) (GU 23)",
    "Straight Armbar - Mount (GU 9) | Guillotine Defense (GU 32)",
    "Triangle Choke - Gaurd (GU 10) | Haymaker Punch Defense (GU 30)",
    "Elevator Sweep - Gaurd (GU 11) | Rear Takedown (GU 29)",
    "Elbow Escape - Mount (GU 12) | Pull Guard (GU 21)",
    "Position Control - Side Mount (GU 13) | Double Leg Takedown (Aggressive) (GU 17)",
    "Headlock Counters - Mount (GU 16) | Standing Headlock Defense (GU 26)",
    "Headlock Escape 1 - Side Mount (GU 18) | Straight Armbar - Guard (GU 34)",
    "Straight Armbar - Guard (GU 19) | Clinch (Aggressive Opponent) (GU 7)",
    "Double Ankle Sweep - Guard (GU 20) | Guillotine Choke (Gaurd Pull) (GU 23)",
  ],
  "Women Empowered": [],
  "Reflex Developement": [],
  "Jr Grapplers": [],
  "Black Belt Club": [],
  "Private Lesson": [],
  "Group Lesson": [],
  "WE Seminar": [],
  "GC Seminar": [],
  "Gracie Game Day": [],
  "Parent's Day": [],
  "Open Mat": [],
  "Little Champs": [],
};
